services:
  chatbot:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAX_FILES=${MAX_FILES}
    volumes:
      - ./.persistence:/app/chromadb_store_en